require: rubocop-rspec

AllCops:
  Exclude:
    - 'db/**/*'
    - 'bin/**/*'

RSpec/ExampleLength:
  Max: 20

Metrics/MethodLength:
  Max: 15

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
